### PR TITLE
Translate git cheat sheet to Traditional Chinese

### PR DESCRIPTION
**Pull request by muan**
:sparkles:

### CODE REVIEW

**Comment by muan** [comment]
@JuanitoFatas :grimacing:

**Comment by JuanitoFatas** [comment]
@muan Done :blush:. Please take a look. After your reviewed, let's get more crowd to review this? Thanks!

P.S. I use [國家教育研究院雙語詞彙、學術名詞暨辭書資訊網](http://terms.naer.edu.tw/) & [Microsoft 語言入口網站](http://www.microsoft.com/Language/zh-tw/Search.aspx) for reference :books:.

**Comment by muan** [comment]
@JuanitoFatas omg didnt expect you to just breeze through this. thank you so much! I'll get on it.

**Comment by JuanitoFatas** [comment]
@muan :ok_hand:

**Comment by muan** [comment]
我覺得很多用詞都太學術了（make sense from your references），但這個小抄目的在希望大家能夠輕鬆理解這些概念，所以以上大部分的建議都是希望都用較為口語的字眼。

謝謝！！！！！

:seedling::seedling::seedling::seedling::seedling::seedling::horse::seedling::horse::seedling::seedling::seedling:
:seedling::seedling::seedling::seedling::seedling::seedling::horse::horse::horse::seedling::seedling::seedling:
:seedling::seedling::seedling::seedling::seedling::black_medium_square::black_medium_square::black_medium_square::horse::black_medium_square::seedling::seedling:
:seedling::seedling::seedling::seedling::horse::horse::horse::horse::horse::black_medium_square::black_medium_square::seedling:
:seedling::seedling::seedling::horse::horse::horse::horse::horse::horse::black_medium_square::black_medium_square::black_medium_square:
:seedling::seedling::horse::horse::horse::black_circle::horse::horse::horse::horse::black_medium_square::black_medium_square:
:seedling::white_circle::horse::horse::horse::horse::horse::horse::horse::horse::horse::black_medium_square:
:white_circle::white_circle::white_circle::horse::horse::horse::horse::horse::horse::horse::horse::horse:
:white_circle::white_circle::white_circle::horse::horse::horse::horse::horse::horse::horse::horse::horse:
:white_circle::white_circle::seedling::seedling::seedling::seedling::seedling::seedling::horse::horse::horse::horse:
:seedling::seedling::seedling::seedling::seedling::seedling::seedling::seedling::horse::horse::horse::horse:
:seedling::seedling::seedling::seedling::seedling::seedling::seedling::seedling::horse::horse::horse::horse:

**Comment by JuanitoFatas** [comment]
> 我覺得很多用詞都太學術了（make sense from your references），但這個小抄目的在希望大家能夠輕鬆理解這些概念，所以以上大部分的建議都是希望都用較為口語的字眼。

:wink: 稍晚更新，多謝 Review。

**Comment by JuanitoFatas** [comment]
我自己又讀了一次，想改成這樣，妳覺得呢？

`````` diff
diff --git a/downloads/zh-TW/github-git-cheat-sheet.md b/downloads/zh-TW/github-git-cheat-sheet.md
index 7c7533b..022de5b 100644
--- a/downloads/zh-TW/github-git-cheat-sheet.md
+++ b/downloads/zh-TW/github-git-cheat-sheet.md
@@ -9,6 +9,7 @@ leadingpath: ../../

 Git 是個開源分散式的版本管理系統，協助 GitHub 在你的電腦上作業。這份小抄總結了常用的 Git 指令，給你做快速參考。

+
 ## 安裝 Git

 GitHub 提供桌面客戶端，包含了圖形化使用介面，可以執行常見的程式庫指令。軟體同時也會自動更新電腦終端機上的 Git 版本，以供進階使用者使用。
@@ -27,9 +28,10 @@ Linux 與 POSIX 系統的 Git 發行版可以在 Git SCM 官網取得。

 http://git-scm.com

+
 ## 設定工具

-為本機所有的程式庫設定使用者資訊
+設定本機所有程式庫的使用者資訊


 ```$ git config --global user.name "[name]"```
@@ -58,6 +60,7 @@ http://git-scm.com


 ```$ git clone [url]```
+
 下載專案連同完整的版本記錄


@@ -68,7 +71,7 @@ http://git-scm.com

 ```$ git status```

-列出所有將會被提交的新檔案、或被修改過的檔案
+列出所有將會提交的新檔案、或修改過的檔案


 ```$ git diff```
@@ -95,14 +98,15 @@ http://git-scm.com

 將檔案快照永久記錄到版本歷史

+
 ## 整理變更

-將一系列的提交內容命名並合併成果
+命名一系列的提交內容並合併成果


 ```$ git branch```

-列出目前程式庫所有的本機分支
+列出目前程式庫所有在本機的分支


 ```$ git branch [branch-name]```
@@ -137,13 +141,14 @@ http://git-scm.com

 ```$ git rm --cached [file]```

-將檔案從版本控制移除但在本機保留檔案
+將檔案從版本控制移除但仍在本機保留檔案


 ```$ git mv [file-original] [file-renamed]```

 變更檔案名稱並將檔案加入工作階段

+
 ## 避免追蹤

 設定例外的暫存檔案與路徑
@@ -161,19 +166,20 @@ temp-*

 列出專案中所有忽略的檔案

+
 ## 儲存片段

-擱置與還原未完成的修改
+擱置與還原未完成的修改內容


 ```$ git stash```

-暫時儲藏所有已追蹤檔案的修改
+暫時儲藏所有已追蹤檔案的修改內容


 ```$ git stash pop```

-拿出最近一次的儲藏的檔案
+拿出最近一次儲藏的檔案


 ```$ git stash list```
@@ -187,7 +193,7 @@ temp-*

 ## 檢閱歷史

-瀏覽與檢查專案檔案的變化
+瀏覽與檢查專案檔案的修改歷史


 ```$ git log```
@@ -209,6 +215,7 @@ temp-*

 顯示特定提交的配置資料及修改內容

+
 ## 重新提交

 去除錯誤並手工修改歷史
@@ -216,13 +223,14 @@ temp-*

 ```$ git reset [commit]```

-取消所有指定提交之後的內容修改記錄，並在本機上保留這些的內容
+取消所有指定提交之後的內容修改記錄，並在本機上保留這些內容


 ```$ git reset --hard [commit]```

 捨棄所有指定提交之後的內容修改記錄

+
 ## 同步變更

 註冊一個程式庫書籤並交換版本歷史
@@ -240,7 +248,7 @@ temp-*

 ```$ git push [alias] [branch]```

-上傳本機所有的提交到 GitHub
+推送本機所有的提交到 GitHub


 ```$ git pull```
``````

**Comment by JuanitoFatas** [comment]
- [ ] bookmark 翻譯與否
  
  bookmark 我覺得應該不需要翻譯，因為它就是平常用的 origin 遠端，翻成書籤好像怪怪的。反倒是現在的翻譯沒有提到遠端，妳覺得呢？

**Pull request closed without merging**
